import { Task } from "../task/Task";
import { BaseTool, ToolCallbacks } from "./BaseTool";
/**
 * Parameters accepted by the read_command_output tool.
 */
interface ReadCommandOutputParams {
    /**
     * The artifact file identifier (e.g., "cmd-1706119234567.txt").
     * This is provided in the execute_command output when truncation occurs.
     */
    artifact_id: string;
    /**
     * Optional search pattern (regex or literal string) to filter lines.
     * When provided, only lines matching the pattern are returned.
     */
    search?: string;
    /**
     * Byte offset to start reading from (default: 0).
     * Used for paginating through large outputs.
     */
    offset?: number;
    /**
     * Maximum bytes to return (default: 32KB).
     * Limits the amount of data returned in a single request.
     */
    limit?: number;
}
/**
 * ReadCommandOutputTool allows the LLM to retrieve full command output that was truncated.
 *
 * When `execute_command` produces output exceeding the preview threshold, the full output
 * is persisted to disk by the `OutputInterceptor`. This tool enables the LLM to:
 *
 * 1. **Read full output**: Retrieve the complete command output beyond the preview
 * 2. **Search output**: Filter lines matching a pattern (like grep)
 * 3. **Paginate**: Read large outputs in chunks using offset/limit
 *
 * ## Storage Location
 *
 * Artifacts are stored outside the workspace in the task directory:
 * `globalStoragePath/tasks/{taskId}/command-output/cmd-{executionId}.txt`
 *
 * ## Security
 *
 * The tool validates artifact_id format to prevent path traversal attacks.
 * Only files matching `cmd-{digits}.txt` pattern are accessible.
 *
 * ## Usage Flow
 *
 * 1. LLM calls `execute_command` which runs a command
 * 2. If output is large, response includes `artifact_id` and truncation notice
 * 3. LLM calls `read_command_output` with the artifact_id to get more content
 *
 * @example
 * ```typescript
 * // Basic usage - read from beginning
 * await readCommandOutputTool.execute({
 *   artifact_id: "cmd-1706119234567.txt"
 * }, task, callbacks);
 *
 * // Search for specific content
 * await readCommandOutputTool.execute({
 *   artifact_id: "cmd-1706119234567.txt",
 *   search: "error|failed"
 * }, task, callbacks);
 *
 * // Paginate through large output
 * await readCommandOutputTool.execute({
 *   artifact_id: "cmd-1706119234567.txt",
 *   offset: 32768,  // Start after first 32KB
 *   limit: 32768    // Read next 32KB
 * }, task, callbacks);
 * ```
 */
export declare class ReadCommandOutputTool extends BaseTool<"read_command_output"> {
    readonly name: "read_command_output";
    /**
     * Execute the read_command_output tool.
     *
     * Reads persisted command output from disk, supporting both full reads and
     * search-based filtering. Results include line numbers for easy reference.
     *
     * @param params - The tool parameters including artifact_id and optional search/pagination
     * @param task - The current task instance for error reporting and state management
     * @param callbacks - Callbacks for pushing tool results
     */
    execute(params: ReadCommandOutputParams, task: Task, callbacks: ToolCallbacks): Promise<void>;
    /**
     * Validate artifact_id format to prevent path traversal attacks.
     *
     * Only accepts IDs matching the pattern `cmd-{digits}.txt` which are
     * generated by the OutputInterceptor. This prevents malicious paths
     * like `../../../etc/passwd` from being used.
     *
     * @param artifactId - The artifact ID to validate
     * @returns `true` if the format is valid, `false` otherwise
     * @private
     */
    private isValidArtifactId;
    /**
     * Read artifact content with offset and limit, adding line numbers.
     *
     * Performs efficient partial file reads using file handles and positional
     * reads. Line numbers are calculated by counting newlines in the portion
     * of the file before the offset.
     *
     * @param artifactPath - Absolute path to the artifact file
     * @param offset - Byte offset to start reading from
     * @param limit - Maximum bytes to read
     * @param totalSize - Total size of the file in bytes
     * @returns Formatted output with header metadata and line-numbered content
     * @private
     */
    private readArtifact;
    /**
     * Search artifact content for lines matching a pattern using chunked streaming.
     *
     * Performs grep-like searching through the artifact file using bounded memory.
     * Instead of loading the entire file into memory, this reads in fixed-size chunks
     * and processes lines as they are encountered. This keeps memory usage predictable
     * even for very large command outputs (e.g., 100MB+ build logs).
     *
     * The pattern is treated as a case-insensitive regex. If the pattern is invalid
     * regex syntax, it's escaped and treated as a literal string.
     *
     * Results are limited by the byte limit to prevent excessive output.
     *
     * @param artifactPath - Absolute path to the artifact file
     * @param pattern - Search pattern (regex or literal string)
     * @param totalSize - Total size of the file in bytes (for display)
     * @param limit - Maximum bytes of matching content to return
     * @returns Formatted output with matching lines and their line numbers
     * @private
     */
    private searchInArtifact;
    /**
     * Add line numbers to content for easier reference.
     *
     * Each line is prefixed with its line number, right-padded to align
     * all line numbers in the output.
     *
     * @param content - The text content to add line numbers to
     * @param startLine - The line number for the first line
     * @returns Content with line numbers prefixed to each line
     * @private
     */
    private addLineNumbers;
    /**
     * Format a byte count to a human-readable string.
     *
     * @param bytes - The byte count to format
     * @returns Human-readable string (e.g., "1.5KB", "2.3MB")
     * @private
     */
    private formatBytes;
    /**
     * Escape special regex characters in a string for literal matching.
     *
     * @param string - The string to escape
     * @returns The escaped string safe for use in a RegExp constructor
     * @private
     */
    private escapeRegExp;
    /**
     * Count newlines before a given byte offset using fixed-size chunks.
     *
     * This avoids allocating a buffer of size `offset` which could be huge
     * for large files. Instead, we read in 64KB chunks and count newlines.
     *
     * @param fileHandle - Open file handle for reading
     * @param offset - The byte offset to count newlines up to
     * @returns The line number at the given offset (1-indexed)
     * @private
     */
    private countNewlinesBeforeOffset;
}
/** Singleton instance of the ReadCommandOutputTool */
export declare const readCommandOutputTool: ReadCommandOutputTool;
export {};
//# sourceMappingURL=ReadCommandOutputTool.d.ts.map