import { Anthropic } from "@anthropic-ai/sdk";
import { ApiHandlerOptions } from "../../shared/api";
import { ApiStream } from "../transform/stream";
import type { SingleCompletionHandler, ApiHandlerCreateMessageMetadata } from "../index";
import { RouterProvider } from "./router-provider";
/**
 * LiteLLM provider handler
 *
 * This handler uses the LiteLLM API to proxy requests to various LLM providers.
 * It follows the OpenAI API format for compatibility.
 */
export declare class LiteLLMHandler extends RouterProvider implements SingleCompletionHandler {
    constructor(options: ApiHandlerOptions);
    private isGpt5;
    /**
     * Detect if the model is a Gemini model that requires thought signature handling.
     * Gemini 3 models validate thought signatures for tool/function calling steps.
     */
    private isGeminiModel;
    /**
     * Inject thought signatures for Gemini models via provider_specific_fields.
     * This is required when switching from other models to Gemini to satisfy API validation
     * for function calls that weren't generated by Gemini (and thus lack thought signatures).
     *
     * Per LiteLLM documentation:
     * - Thought signatures are stored in provider_specific_fields.thought_signature of tool calls
     * - The dummy signature base64("skip_thought_signature_validator") bypasses validation
     *
     * We inject the dummy signature on EVERY tool call unconditionally to ensure Gemini
     * doesn't complain about missing/corrupted signatures when conversation history
     * contains tool calls from other models (like Claude).
     */
    private injectThoughtSignatureForGemini;
    createMessage(systemPrompt: string, messages: Anthropic.Messages.MessageParam[], metadata?: ApiHandlerCreateMessageMetadata): ApiStream;
    completePrompt(prompt: string): Promise<string>;
}
//# sourceMappingURL=lite-llm.d.ts.map